name: sembast_sqflite_001
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  sembast_sqflite: ^2.2.0+1
  sqflite_common: ^2.5.4+2
  sembast: ^3.0.0
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
